### ISSUE TITLE
Slideshow is not displayed on DAB+ radios

### ISSUE THREAD

**Issue by vanhauser-thc** [Opendigitalradio/ODR-PadEnc#5]
Hi,

I am using odr-padenc to create a stream for dls and slideshow like this:

```
odr-padenc -v -r -p 196 -t dls.txt -o /tmp/dls.fifo -s 2 -d /opt/resources/images
```

The images directory contains several pictures. odr-padenc is compiled with magickwand.
When running the command I see from the output messages that it creates a stream that writes the text and rotates through the images in the images directory.

In dabmux I combine that stream with a dabp from audioenc and then send it via dabmod.

The music can be heard, the DLS text is visible - but no images are displayed on either (2 different) dab+ radio. both are able to display slideshow images (as tested with other stations).

so - is this feature broken?

**Comment by basicmaster** [comment]
Hi,

no, this feature is working and in production use.

Do you have the [Slideshow signalling](http://wiki.opendigitalradio.org/ODR-PadEnc#Service_signalling) enabled in the multiplex settings?

If so, which DAB+ radios do you use?

P.S. You might want to use the [Uniform Mode](http://wiki.opendigitalradio.org/ODR-PadEnc#Uniform_mode_.28recommended.29) instead of the Burst Mode, to better utilize the available PAD bandwidth.

**Comment by vanhauser-thc** [comment]
I was missing the figtype entry in DabMux ... inserting that then showed the slideshow.

the advanced.mux example file could need some better example. for me the wording seems to imply that I need to enable "datagroup true" in components. but when I do that dabmux fails with an error that I dont understand. leaving that setting out lets dabmux run and also shows the slideshow then.

also is "type 0" or "type 60" a necessary option?

thats all not clear for me when I try to understand advanced.mux :)

**Comment by mpbraendli** [comment]
Hi,
I'm always interested in improving the documentation, and the `advanced.mux` file is part of it.
The `datagroup` option is for packet mode subchannels, not for PAD (Programme-associated data) that is carried inside an audio subchannel.

I agree a little sentence that explains that `figtype 0x2` is required for slides to work in the ODR-PadEnc + ODR-AudioEnc scenario would be nice. I would like to invite you to send a small patch or pull request.

Closing issue because original problem fixed.
